# Generated by Django 3.0.8 on 2020-07-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='images/')),
                ('product_desc', models.TextField(blank=True)),
                ('product_title', models.CharField(max_length=200)),
                ('product_date', models.DateField()),
                ('product_icon', models.ImageField(height_field=50, upload_to='images/', width_field=50)),
                ('product_url', models.TextField()),
                ('product_votes', models.IntegerField(default=1)),
            ],
        ),
    ]
